# list of indexes
DESTINATION_INDEX = 0
AIRCOMPANY_INDEX = 1
FLIGHT_NUMBER = 2
ESTIMATED_HOUR_INDEX= 3
HOUR_DEPARTURE_INDEX = 4
HOUR_ARRIVAL_INDEX = 5
TERMINAL_DEPARTURE_INDEX = 6
GATE_DEPARTURE_INDEX = 7
TERMINAL_ARRIVAL_INDEX = 8
GATE_ARRIVAL_INDEX = 9
STATUS_INDEX = 10

HOUR_DEPARTURE_INDEX_DETAILED = 0
TERMINAL_DEPARTURE_INDEX_DETAILED = 1
GATE_DEPARTURE_INDEX_DETAILED = 2
HOUR_ARRIVAL_INDEX_DETAILED = 3
TERMINAL_ARRIVAL_INDEX_DETAILED = 4
GATE_ARRIVAL_INDEX_DETAILED = 5
FIRST_FLIGHT_INDEX = 0
FIRST_ROW = 1 # first row no including title
REMOVE_S = -1 # remove s from departure and arrivals from user input

times = [0, 6, 12, 18]

to_from = ["departures", "arrivals"]
